name: publish
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/riyad1721/hello-docker-gcr-demo:latest
      - name: Save Docker image to disk
        run: |
          docker save ghcr.io/riyad1721/hello-docker-gcr-demo:latest -o hello-docker-image.tar
      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: hello-docker-image
          path: hello-docker-image.tar

  push-docker-image:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: hello-docker-image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Load Docker image
        run: |
          docker load -i hello-docker-image.tar
      - name: Push the hello-docker Docker image
        run: |
          docker push ghcr.io/riyad1721/hello-docker-gcr-demo:latest
