# .github/workflows/push-docker-image.yml
name: Push Docker Image

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: hello-docker-image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Load Docker image
        run: |
          docker load -i hello-docker-image.tar
      - name: Push the hello-docker Docker image
        run: |
          docker push ghcr.io/riyad1721/hello-docker-gcr-demo:latest
